Repository CodeSecure-Inc/jenkins-codesonar-plugin, pull requests merged in 2023-11, with the labels that each got.

#20 Added new parameter comparisonAnalysis to the plugin
  README.md
  src/main/java/org/jenkinsci/plugins/codesonar/CodeSonarJobDslContext.java
  src/main/java/org/jenkinsci/plugins/codesonar/CodeSonarJobDslExtension.java
  src/main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java
  src/main/resources/org/jenkinsci/plugins/codesonar/CodeSonarPublisher/config.jelly
  src/main/resources/org/jenkinsci/plugins/codesonar/CodeSonarPublisher/help-comparisonAnalysis.html
Labels: enhancement

#21 Refactor some credential handling and HTTP code, fix some bugs
  pom.xml
  src/main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/AlertsService.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/AuthenticationService.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/CodeSonarHubAnalysisDataLoader.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/HttpService.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/HttpServiceRequest.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/HttpServiceResponse.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/WarningsService.java
  src/test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java
Labels: bug

#22 Rebrand for CodeSecure
  CONTRIBUTING.md
  README.md
  pom.xml
  src/main/resources/index.jelly
  test/README.md
  test/codesonar-reset-UNACCEPTED_LICENSE.txt
  test/wgen-codesonar-template.conf
  test/wgen.py
Labels: documentation, cosmetic

#23 Support CodeSonar user session pooling.
  src/main/java/org/jenkinsci/plugins/codesonar/models/CodeSonarHubCapabilityInfo.java
  src/main/java/org/jenkinsci/plugins/codesonar/models/CodeSonarHubInfo.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/AuthenticationService.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/HttpService.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/HttpServiceRequest.java
  src/main/java/org/jenkinsci/plugins/codesonar/services/HubInfoService.java
Labels: enhancement
